#!/usr/bin/env bash

# A script to find missing snapshots
# Author: Sanghyuk Moon
# Date: August 2019

# function to print help message and exit
usage() { 
  cat <<EOM
  -------------------------------------------------------------------
  Usage: fcheck PREFIX POSTFIX START END
                (PREFIX.####.POSTFIX)
  -------------------------------------------------------------------
EOM
  exit 1 
}


# parse options and arguments using getopts
while getopts :h opt; do
  case $opt in
    h) usage;;
    \?) usage;;
  esac
done
shift "$((OPTIND-1))"
PREFIX=$1
POSTFIX=$2
START=$3
END=$4
STEP=1

for i in $(seq -f "%04g" $START $STEP $END); do
  FILE=$PREFIX.$i.$POSTFIX
  [ ! -f "$FILE" ] && echo "$FILE does not exist"
done
