#!/usr/bin/env bash

# A script to find missing snapshots
# Author: Sanghyuk Moon
# Date: August 2019

# function to print help message and exit
usage() { 
  cat <<EOM
  -------------------------------------------------------------------
  Usage: fcheck START END
  -------------------------------------------------------------------
EOM
  exit 1 
}


# parse options and arguments using getopts
while getopts :h opt; do
  case $opt in
    h) usage;;
    \?) usage;;
  esac
done
shift "$((OPTIND-1))"
START=$1
END=$2
STEP=1

for i in $(seq -f "%04g" $START $STEP $END); do
  FILE=gc.$i.vtk
#  if [ -f "$FILE" ]; then
#    echo "$FILE exist"
#  fi
  [ ! -f "$FILE" ] && echo "$FILE does not exist"
done
