#!/usr/bin/env bash

# A simple find wrapper
# Author: Sanghyuk Moon
# Date: Feb 2025

# function to print help message and exit
usage() { 
  cat <<EOM
  -------------------------------------------------------------------
  Usage: findrecent [-d] "PATTERN" (+-)DAYS_OLD

  -d Delete matched files instead of printing them

  Plus sign for older than DAYS_OLD files
  Minus sign for newer than DAYS_OLD files
  -------------------------------------------------------------------
EOM
  exit 1 
}

if (( $# == 0 )); then
  usage
  exit 1
fi

delete_matches=false

# parse options and arguments using getopts 
while getopts :hd opt; do
  case $opt in
    h) usage;;
    d) delete_matches=true;;
    \?) usage;;
  esac
done
shift "$((OPTIND-1))"

if [[ "$delete_matches" == true ]]; then
  find . -maxdepth 1 -name "$1" -mtime $2 -delete
else
  find . -maxdepth 1 -name "$1" -mtime $2 -printf "%Tb %Td %TH:%TM %f\n"
fi
