#!/usr/bin/env bash

# A short script for movie making
# Author: Sanghyuk Moon
# Date: July 2019
# references:
# https://en.wikibooks.org/wiki/FFMPEG_An_Intermediate_Guide/image_sequence#Not_numbered_or_no_regular_pattern
#

# function to print help message and exit
usage() { 
  cat <<EOM
  $0 -p <PREFIX> [-s SRCDIR] [-d DSTDIR] [-f FRAMERATE] [-l]"
  -p <PREFIX> e.g., all.M1_2pc, etc.
  -s <SRCDIR> Directory where the source images files are located. Default to the current dir.
  -d <DSTDIR> Directory where the output movie file is to be stored. Default to the current dir.
  -f <FRAMERATE> Frame rate (Default = 10).
  -l make lossless video (cannot open in Windows Media Player but mpv)
EOM
  exit 1 
}

SRCDIR="."
DSTDIR="."
FRATE=10
LOSSLESS=0

# parse options and arguments using getopts 
while getopts :hp:s:d:f:l opt; do
  case $opt in
    h) usage;;
    p) PREFIX=$OPTARG;;
    s) SRCDIR=$OPTARG;;
    d) DSTDIR=$OPTARG;;
    f) FRATE=$OPTARG;;
    l) LOSSLESS=1;;
    \?) usage;;
  esac
done
shift "$((OPTIND-1))"
(( $# != 0 )) && usage # positional argument is not allowed

[ -z "$PREFIX" ] && usage

if [ $LOSSLESS -eq 1 ]
then
  # lossless video from the png images
  ffmpeg -y -framerate $FRATE -pattern_type glob -i "$SRCDIR/$PREFIX.?????.png" -codec:v copy $DSTDIR/$PREFIX.lossless.mp4
else
  # windows-playable format
  ffmpeg -y -framerate $FRATE -pattern_type glob -i "$SRCDIR/$PREFIX.?????.png" -c:v libx264 -pix_fmt yuv420p -vf "scale=trunc(iw/2)*2:trunc(ih/2)*2" $DSTDIR/$PREFIX.mp4
fi
