#!/usr/bin/env bash

# A simple rsync wrapper for moving data across machines
# Author: Sanghyuk Moon
# Date: July 2019

# function to print help message and exit
usage() { 
  cat <<EOM
  -------------------------------------------------------------------
  Usage: pmv [-t] SRC DST
  -------------------------------------------------------------------
  Options:
  -t Review command before execution
  -------------------------------------------------------------------

EOM
  exit 1 
}

if (( $# == 0 )); then
  usage
  exit 1
fi

RSYNC="rsync --archive --progress --remove-source-files --partial-dir=.rsync-partial --exclude '*.txt' --exclude '*.dat' --exclude '*.hst' --exclude '*.sn' --exclude '*.rst' --exclude 'job' --exclude 'athinput*' --exclude 'tigress_gc_hd'"
REVIEW=0

# parse options and arguments using getopts 
while getopts :hrt opt; do
  case $opt in
    h) usage;;
    t) REVIEW=1;;
    \?) usage;;
  esac
done
shift "$((OPTIND-1))"
SRC=$1
DST=$2

if (( $REVIEW == 1 )); then
  echo $RSYNC $SRC $DST
else
  $RSYNC $SRC $DST
fi
