#!/usr/bin/env bash

# A script to mv data to tigress
# Author: Sanghyuk Moon
# Date: Jan 2020

# function to print help message and exit
usage() { 
  cat <<EOM
  -------------------------------------------------------------------
  Usage: pmv [-s] [-d] [-t] INDIR START END
  -------------------------------------------------------------------
  Options:
  -s source (default: current directory)
  -d destination (default: /tigress/sm69)
  -t Review command before execution
  -------------------------------------------------------------------
  Examples: pmv N2_512 0 10
  -------------------------------------------------------------------
EOM
  exit 1 
}

if (( $# == 0 )); then
  usage
  exit 1
fi

SRC=.
DST=/tigress/sm69
REVIEW=0

# parse options and arguments using getopts
while getopts :hs:d:t opt; do
  case $opt in
    h) usage;;
    s) SRC=$OPTARG;;
    d) DST=$OPTARG;;
    t) REVIEW=1;;
    \?) usage;;
  esac
done
shift "$((OPTIND-1))"
INDIR=$1
START=$2
END=$3
FLIST=pmv_file_list_$INDIR.txt

if (( $REVIEW == 1 )); then
  echo 'for i in $(seq $START $END)'
  echo 'do'
  echo '  ls $INDIR/id*/gc*.`printf "%04d" $i`.*vtk > $FLIST'
  echo 'done'
  echo 'rsync -a --remove-source-files --files-from $FLIST $SRC $DST'
  echo 'rm $FLIST'
else
  for i in $(seq $START $END)
  do
    ls $INDIR/id*/gc*.`printf "%04d" $i`.*vtk >> $FLIST
  done
  rsync --archive --progress --remove-source-files --files-from $FLIST $SRC $DST
  rm $FLIST
fi
