#!/usr/bin/env bash

# A script to find missing snapshots
# Author: Sanghyuk Moon
# Date: August 2019

# function to print help message and exit
usage() { 
  cat <<EOM
  -------------------------------------------------------------------
  Usage: fcheck [-r] [-t] SRC DST
  -------------------------------------------------------------------
  Options:
  -r Remove source files (turn on rsync --remove-source-files option)
  -t Review command before execution
  -------------------------------------------------------------------
  Examples:
  1. transfer a whole directory "machine:/path/to/dir" to "/path/to/local/dir" and remove source files
     \$ mvdata -r machine:/path/to/dir /path/to/local
  2. copy all files under "machine:/path/to/dir" into /path/to/local/dir
     \$ mvdata machine:/path/to/dir/ /path/to/local/dir
  * WARNING: Trailing slash in SRC changes the behavior
  * Note   : you may need to add machine in .ssh/config file
  -------------------------------------------------------------------
EOM
  exit 1 
}


DSTDIR=/home/smoon/data/gc/M1_4pc/vtk
SRCDIR=/home/smoon/data/gc/M1_4pc_rst1

START=0
STEP=1
END=1106

for i in $(seq -f "%04g" $START $STEP $END); do
  FILE=$DSTDIR/gc.$i.vtk
  if [ -f "$FILE" ]; then
    echo "$FILE exist"
    find $SRCDIR/id* -name "gc*.$i.vtk" -delete
  fi
#  [ ! -f "$FILE" ] && echo "$FILE does not exist"
done
